### PR TITLE
add CI to set the stage for running fontbakery

### PR DESCRIPTION
**Pull request by joefitzgerald**
This PR includes portions of https://github.com/chrismsimpson/Metropolis/pull/35/commits/0b2fb1ff6125d95a9fd7f3ecb5e34a2b0dbcc07d, and sets the stage for running fontmaker and fontbakery in subsequent PRs.

- fontmake cannot be run yet; it returns an error (https://github.com/chrismsimpson/Metropolis/pull/35/commits/1b143bec257e5c2d37d760f4eb83db4219e88c75 seems to indicate that the following will fix the build issues: adding a Light[700] bracket layer for each of the glyphs that were causing fontmake builds to fail: the cent and the dollar on both the Regular and the Italic)
- subsequent steps are commented out so that they can be enabled progressively in subsequent PRs

Related to #35.

### CODE REVIEW

**Comment by chrismsimpson** [comment]
Nice! I’ll take a look when I have a moment

**Comment by joefitzgerald** [comment]
Cool, thanks @chrismsimpson. You will need to enable Travis CI by going to https://travis-ci.org and toggling on this repo. Here is an example of a working build (albeit one that is not doing much that is interesting *at this stage*, until we uncomment some of the lines in the script in successive PRs): https://travis-ci.org/github/joefitzgerald/Metropolis.

**Comment by joefitzgerald** [comment]
Hey @chrismsimpson I just wanted to articulate my intended approach for subsequent PRs. #35 contains items that you wanted to evaluate independently.

I intend to open the subsequent PRs *after* this PR is merged so that Travis is turned on for the repo and so that we can see each PR resulting in successful builds as lines in the CI script are uncommented. This should give us the ability to discuss each change in isolation and use the Travis to validate our progress.

I will likely open a PR for each commit in #35, although I may break some of the commits into multiple PRs, or batch two or more minor commits into a single PR.

I don't intend to make any license related PR, as I think you need to independently make decisions about how you license the font, and it's not my place to push you in any direction.

**Comment by chrismsimpson** [comment]
Is there any particular reason why the `build.sh` has to go in a directory named `CI`? I would be happy/prefer this to go in the `Sources` directory

**Comment by joefitzgerald** [comment]
@chrismsimpson I'm fine with that. Changes pushed.

**Comment by joefitzgerald** [comment]
@chrismsimpson thanks for merging. Please make sure you remember to turn on travis-ci for this repo, or it won’t run on new commits.

**Pull request merged**
