### PR TITLE
[VMware Updates] Added Light Italic, Semibold weights; Added trademar…

### PR DESCRIPTION
**Pull request by mathisscott**
…k and registration symbols; Fixed Capital 'S' issue

_Describe the change or feature in detail. Try to answer the following questions._

* What are the changes? Tell us why for each one, if possible.
Added Semibold and Light Italic weight.

Addition of both the Trademark symbol (™) and the Registration symbol (®) to all weights. These characters are needed for representing properties or entities that are trademarks or registered trademarks of an individual or corporation.

Adjusted the sizing of the capital "S" to be more consistent with the sizing of the rest of the capital letterforms.

* Why should it go in Metropolis?
The Trademark and Registration symbols are often required by the legal departments of corporations to clarify legal ownership of intellectual property.
The adjusted size of the capital "S" makes upper case treatments more consistent across all letterforms.

_Provide some specific details about how this change would improve your application and use case._

If referencing products that are the registered intellectual property of a person or corporation, it is necessary to add the Trademark or Registration symbol (as applicable) on first mention. This can also be done by writing out "Product X is a registered trademark of Person or Corporation Y", however using the symbols saves space and is a best-practices preferred treatment.

When using an all upper case type style, the uniformity of the capital S creates a cleaner final typographic treatment.

### CODE REVIEW

**Comment by jtyler666** [comment]
Hi Chris, checking to see if you've had a chance to review this yet and see if you would have an ETA for when the updates might push live?
Thanks,
Jef

**Comment by jeftyler** [comment]
Hi Chris,
I'm checking to see if you have a possible ETA for when the update will push live, working with our brand group to make sure we're aligned. Reach out with any questions.
Thanks,
Jef

**Comment by mathisscott** [comment]
Hi @chrismsimpson 
Any updates here?

**Comment by mathisscott** [comment]
Hi @chrismsimpson 
It's been awhile. Should I call out the detectives? 😄

**Comment by chrismsimpson** [comment]
Hey @mathisscott, I tried looking at this commit, there's a lot of commits to various files, are you able reduce this to a PR that only has commits to the *.glyphs files. Also, you may need to pull from the latest master, I have been doing a lot of tidy up lately and committing it directly to master :)

**Comment by mathisscott** [comment]
@chrismsimpson 
I'm working on reducing the commit to only *.glyphs files. But since you've made changes to the *.glyphs files we have a merge conflict. It appears these files are mostly XML? But I don't have the Glyphs program and wouldn't know where to start to validate these merge conflicts.

I'm a dev who is creating a pull request for the team that made these changes. Should I try to handle the merge conflicts and hope for the best? What would you advise?

**Comment by chrismsimpson** [comment]
Hey @mathisscott 👋 Best alternative is to send through an email (it's in the README) with SVGs or PDFs with a relative sized artboard (1000em sq) and describe the changes.

**Pull request closed without merging**
